Benchmark and API tweaks
open-spaced-repetition/fsrs-optimizer-rs pull request #59
Opened 2023-09-09 02:02 UTC by dae

What do you think about the new API?

2023-09-09 03:44 UTC, dae commented
Hmm. Thinking more about it, I wonder whether using the saved stability might be better than passing in the whole revlog. In https://github.com/open-spaced-repetition/rs-fsrs/issues/6#issuecomment-1711109835 you said that this would be incorrect when the user changes their weights. But when they change their weights, couldn't we automatically apply the updated stability to all cards using that preset? This would mean less work needs to be done during review, and would be easier to integrate into Anki, as Anki's state handling code doesn't currently have access to the revlog history. WDYT?

2023-09-09 04:56 UTC, L-M-Sherlock commented
> But when they change their weights, couldn't we automatically apply the updated stability to all cards using that preset?

Yes, we can use `calc_memo_state` here to update them in batch. It's more efficient and convenient.

2023-09-09 05:01 UTC, dae commented
Great, I'll refactor this PR.

2023-09-09 05:27 UTC, dae commented
One remaining problem is that without access to the revlog history, we don't know what `i` should be. And we can't just do a simple "select count(*) from revlog where cid=?", because we need the logic that discards reviews after rescheduling. It would be nice if we could avoid looking at the revlog during review.

Maybe one way to optimize this would be to store `i` as another custom_data  value, and remove it when manually rescheduling.  If missing from custom_data, it could be calculated based on the revlog history at review time. Do you foresee any problems with such an approach?

2023-09-09 06:44 UTC, L-M-Sherlock commented
> One remaining problem is that without access to the revlog history, we don't know what `i` should be.

Actually, it's not necessary to get the exact length of the revlog history. `i` is used to distinguish whether it is the first review. Because in the first review, previous memo state doesn't exist, and FSRS need to initialize the memo state from the first rating.

2023-09-10 03:20 UTC, dae commented
I've refactored things so there's a top-level Fsrs struct that users will import, and it can use like this:

```rust
        let fsrs = Fsrs::new(Some(WEIGHTS));

        # after weight change
        let state = fsrs.memory_state(item);
    
        # during review
        let states = fsrs.next_states(Some(state), 0.9, 21),
```

Does that work for you?

Also since this crate now does both inference and training, what do you think about renaming the repo to fsrs-rs?

2023-09-10 04:21 UTC, L-M-Sherlock commented
> what do you think about renaming the repo to fsrs-rs?

I will change it after merging.

> Does that work for you?

I'm reviewing it in my local device.

2023-09-10 04:35 UTC, L-M-Sherlock requested changes

2023-09-10 04:35 UTC, L-M-Sherlock commented on src/model.rs
> +pub struct Fsrs<B: Backend<FloatElem = f32> = NdArrayBackend> {
It looks weird that only `F` is capital. FSRS is abbreviation of free spaced repetition scheduler. I recommend using `FSRS` here.

2023-09-10 04:35 UTC, L-M-Sherlock commented on src/inference.rs
> +        let rmse = calibration_rmse(all_predictions, all_true_val);
To avoid confusion with the common rmse, I recommend renaming `rmse` to `rmse_bins`. And keep its consistency in Anki (RMSE -> RMSE(bins)).

2023-09-10 04:37 UTC, L-M-Sherlock commented
Besides, I meet this error in my vscode:

```
error[E0432]: unresolved import `fsrs_optimizer`
  --> benches/benchmark.rs:10:5
   |
10 | use fsrs_optimizer::FSRSReview;
   |     ^^^^^^^^^^^^^^ use of undeclared crate or module `fsrs_optimizer`
```

2023-09-10 05:08 UTC, L-M-Sherlock approved these changes
LGTM

2023-09-10 05:11 UTC, merged